import { AssetsFormModel } from './assets.models';

export const assetsStub: AssetsFormModel[] = [
  {
    id: '1111',
    anyVehicles: true,
    vehiclesOnCreditBureau: 1,
    collateralVehicles: 1,
    who: 'Applicant',
    category: 'Auto or Truck',
    type: 'Sedan',
    collateral: true,
    reasonNotCollateral: '',
    valuation: {
      year: '2018',
      make: 'Toyota',
      model: 'Camry',
      vin: '1HGBH41JXMN109186',
      mileage: '50000',
      value: '15000',
      ownedFreeAndClear: true,
      autoCheckComplete: true,
      vehicleInspection: true,
      qualifiedForDirectAuto: true,
    },
    salvageTitle: false,
    purchaseMoney: false,
  },
  {
    id: '2222',
    anyVehicles: true,
    vehiclesOnCreditBureau: 1,
    collateralVehicles: 1,
    who: 'Co-Applicant',
    category: 'Auto or Truck',
    type: 'SUV',
    collateral: true,
    reasonNotCollateral: '',
    valuation: {
      year: '2020',
      make: 'Honda',
      model: 'CR-V',
      vin: '1HGBH41JXMN109187',
      mileage: '30000',
      value: '20000',
      ownedFreeAndClear: false,
      autoCheckComplete: true,
      vehicleInspection: true,
      qualifiedForDirectAuto: true,
    },
    salvageTitle: false,
    purchaseMoney: false,
  },
  {
    id: '3333',
    anyVehicles: true,
    vehiclesOnCreditBureau: 1,
    collateralVehicles: 1,
    who: 'Applicant',
    category: 'Auto or Truck',
    type: 'Truck',
    collateral: true,
    reasonNotCollateral: '',
    valuation: {
      year: '2015',
      make: 'Ford',
      model: 'F-150',
      vin: '1HGBH41JXMN109188',
      mileage: '70000',
      value: '18000',
      ownedFreeAndClear: true,
      autoCheckComplete: true,
      vehicleInspection: true,
      qualifiedForDirectAuto: true,
    },
    salvageTitle: true,
    purchaseMoney: false,
  },
];
