query users($options: PageQueryOptions){
    users(options: $options){
        data{
            email
            id
            name
            phone
            username
            website
        }
        meta{
            totalCount
        }
    }
}