/**
 * PREPEND this content to the typescript models file
 */
module.exports = {
  plugin: (schema, documents, config) => {
    // Return the wrapped content
    return `// DO NOT EDIT THIS FILE, IT IS AUTO-GENERATED\n\n// eslint-disable-next-line @typescript-eslint/prefer-namespace-keyword, @typescript-eslint/no-namespace
      export module ${config.wrapModule.name} {`;
  },
};
