// DO NOT EDIT THIS FILE, IT IS AUTO-GENERATED
import { gql } from 'apollo-angular';
// eslint-disable-next-line @typescript-eslint/prefer-namespace-keyword, @typescript-eslint/no-namespace
export module GraphQL {
  export const _Query = gql`
    query _ {
      _ {
        
      }
    }
  `;

  export const AlbumQuery = gql`
    query album {
      album {
        id
        photos
        title
        user
      }
    }
  `;

  export const AlbumsQuery = gql`
    query albums {
      albums {
        data
        links
        meta
      }
    }
  `;

  export const CommentQuery = gql`
    query comment {
      comment {
        body
        email
        id
        name
        post
      }
    }
  `;

  export const CommentsQuery = gql`
    query comments {
      comments {
        data
        links
        meta
      }
    }
  `;

  export const PhotoQuery = gql`
    query photo {
      photo {
        album
        id
        thumbnailUrl
        title
        url
      }
    }
  `;

  export const PhotosQuery = gql`
    query photos {
      photos {
        data
        links
        meta
      }
    }
  `;

  export const PostQuery = gql`
    query post {
      post {
        body
        comments
        id
        title
        user
      }
    }
  `;

  export const PostsQuery = gql`
    query posts {
      posts {
        data
        links
        meta
      }
    }
  `;

  export const TodoQuery = gql`
    query todo {
      todo {
        completed
        id
        title
        user
      }
    }
  `;

  export const TodosQuery = gql`
    query todos {
      todos {
        data
        links
        meta
      }
    }
  `;

  export const UserQuery = gql`
    query user {
      user {
        address
        albums
        company
        email
        id
        name
        phone
        posts
        todos
        username
        website
      }
    }
  `;

  export const UsersQuery = gql`
    query users {
      users {
        data
        links
        meta
      }
    }
  `;

  export const _Mutation = gql`
    mutation _ {
      _ {
        
      }
    }
  `;

  export const AlbumCreateMutation = gql`
    mutation createAlbum {
      createAlbum {
        id
        photos
        title
        user
      }
    }
  `;

  export const CommentCreateMutation = gql`
    mutation createComment {
      createComment {
        body
        email
        id
        name
        post
      }
    }
  `;

  export const PhotoCreateMutation = gql`
    mutation createPhoto {
      createPhoto {
        album
        id
        thumbnailUrl
        title
        url
      }
    }
  `;

  export const PostCreateMutation = gql`
    mutation createPost {
      createPost {
        body
        comments
        id
        title
        user
      }
    }
  `;

  export const TodoCreateMutation = gql`
    mutation createTodo {
      createTodo {
        completed
        id
        title
        user
      }
    }
  `;

  export const UserCreateMutation = gql`
    mutation createUser {
      createUser {
        address
        albums
        company
        email
        id
        name
        phone
        posts
        todos
        username
        website
      }
    }
  `;

  export const AlbumDeleteMutation = gql`
    mutation deleteAlbum {
      deleteAlbum {
        
      }
    }
  `;

  export const CommentDeleteMutation = gql`
    mutation deleteComment {
      deleteComment {
        
      }
    }
  `;

  export const PhotoDeleteMutation = gql`
    mutation deletePhoto {
      deletePhoto {
        
      }
    }
  `;

  export const PostDeleteMutation = gql`
    mutation deletePost {
      deletePost {
        
      }
    }
  `;

  export const TodoDeleteMutation = gql`
    mutation deleteTodo {
      deleteTodo {
        
      }
    }
  `;

  export const UserDeleteMutation = gql`
    mutation deleteUser {
      deleteUser {
        
      }
    }
  `;

  export const AlbumUpdateMutation = gql`
    mutation updateAlbum {
      updateAlbum {
        id
        photos
        title
        user
      }
    }
  `;

  export const CommentUpdateMutation = gql`
    mutation updateComment {
      updateComment {
        body
        email
        id
        name
        post
      }
    }
  `;

  export const PhotoUpdateMutation = gql`
    mutation updatePhoto {
      updatePhoto {
        album
        id
        thumbnailUrl
        title
        url
      }
    }
  `;

  export const PostUpdateMutation = gql`
    mutation updatePost {
      updatePost {
        body
        comments
        id
        title
        user
      }
    }
  `;

  export const TodoUpdateMutation = gql`
    mutation updateTodo {
      updateTodo {
        completed
        id
        title
        user
      }
    }
  `;

  export const UserUpdateMutation = gql`
    mutation updateUser {
      updateUser {
        address
        albums
        company
        email
        id
        name
        phone
        posts
        todos
        username
        website
      }
    }
  `;
}
